tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true

build:
    environment:
        php:
            version: 7.0.0
        redis: false
        postgresql: false
        mongodb: false
    tests:
        override:
            -
                command: 'composer test-cl'
                coverage:
                    file: 'test/clover.xml'
                    format: 'clover'

filter:
    excluded_paths: [vendor/*, test/*]
